[package]
name = "proxy"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.50"
tokio = { version = "1", features = ["full"] }
tokio-postgres = { version = "0.7", features = [] }
pgwire = { path = "../pgwire" }